changesetBaseRefs:
  - head

changesetIgnorePatterns:
  - "**/dist/*"
  - "**/packages/*"
  - "**/.*"
  - .**/*

compressionLevel: mixed

enableGlobalCache: true

logFilters:
  - code: YN0060
    level: discard

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.2.1.cjs
