changesetBaseRefs:
  - head

changesetIgnorePatterns:
  - "**/dist/*"
  - "**/packages/*"
  - "**/.*"
  - .**/*

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules
nmHoistingLimits: none

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
