changesetBaseRefs:
  - head

changesetIgnorePatterns:
  - "**/dist/*"
  - "**/packages/*"
  - "**/.*"
  - .**/*

enableGlobalCache: true

logFilters:
  - code: YN0060
    level: discard

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@uniswap/swap-router-contracts@*":
    peerDependenciesMeta:
      hardhat:
        optional: true
  "@uniswap/v3-periphery@*":
    peerDependenciesMeta:
      hardhat:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
