import { XyoApiBase } from '../../Base'
import { XyoApiSimple } from '../../Simple'

export interface XyoAccountChallenge {
  /** @field Server specific state identifier [out] */
  state?: string
}

export interface XyoAccountVerify {
  /** @field Message that was signed [in] */
  message: string
  /** @field Signature [in] */
  signature: string
  /** @field Token generated by server [out] */
  token?: string
}

export class XyoAccountApi extends XyoApiBase {
  public get challenge() {
    return new XyoApiSimple<XyoAccountChallenge>({
      ...this.config,
      root: `${this.root}challenge/`,
    })
  }

  public get verify() {
    return new XyoApiSimple<XyoAccountVerify>({
      ...this.config,
      root: `${this.root}verify/`,
    })
  }
}
