export const DIVINER_TYPES = {
  AddressHistoryDiviner: Symbol('AddressHistoryDiviner'),
  AddressSpaceBatchDiviner: Symbol('AddressSpaceBatchDiviner'),
  AddressSpaceDiviner: Symbol('AddressSpaceDiviner'),
  BoundWitnessDiviner: Symbol('BoundWitnessDiviner'),
  BoundWitnessStatsDiviner: Symbol('BoundWitnessStatsDiviner'),
  ElevationDiviner: Symbol('ElevationDiviner'),
  ForecastingDiviner: Symbol('ForecastingDiviner'),
  ImageThumbnailDiviner: Symbol('ImageThumbnailDiviner'),
  NftCollectionScoreDiviner: Symbol('NftCollectionScoreDiviner'),
  NftScoreDiviner: Symbol('NftScoreDiviner'),
  PayloadDiviner: Symbol('PayloadDiviner'),
  PayloadStatsDiviner: Symbol('PayloadStatsDiviner'),
  SchemaListDiviner: Symbol('SchemaListDiviner'),
  SchemaStatsDiviner: Symbol('SchemaStatsDiviner'),
}
