import { XyoApiBase } from '../../Base'
import { XyoApiSimple } from '../../Simple'

export interface XyoWalletChallenge {
  /** @field Server spacific state identifier [out] */
  state?: string
}

export interface XyoWalletVerify {
  /** @field Message that was signed [in] */
  message: string
  /** @field Signature [in] */
  signature: string
  /** @field Token generated by server [out] */
  token?: string
}

export class XyoWalletApi extends XyoApiBase {
  public get challenge() {
    return new XyoApiSimple<XyoWalletChallenge>({
      ...this.config,
      root: `${this.root}challenge/`,
    })
  }

  public get verify() {
    return new XyoApiSimple<XyoWalletVerify>({
      ...this.config,
      root: `${this.root}verify/`,
    })
  }
}
