export const terminalCommands = [
  'Describe Node',
  'Show Config',
  'Status',
  'Node Logs',
  'Stop Node',
  'Restart Node',
  'Register Module',
  'Unregister Module',
  'List Registered Modules',
  'Attach Module',
  'Detach Module',
  'List Attached Modules',
  'Exit',
]
