import { TemporalIndexingDivinerSchema } from '../Schema.ts'

export type TemporalIndexingDivinerIndexQueryResponseToDivinerQueryResponseDivinerSchema =
  `${TemporalIndexingDivinerSchema}.stage.indexQueryResponseToDivinerQueryResponseDiviner`
export const TemporalIndexingDivinerIndexQueryResponseToDivinerQueryResponseDivinerSchema: TemporalIndexingDivinerIndexQueryResponseToDivinerQueryResponseDivinerSchema = `${TemporalIndexingDivinerSchema}.stage.indexQueryResponseToDivinerQueryResponseDiviner`
